
spring:
  datasource:
    url: jdbc:postgreesql:/localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: cami
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
